### ISSUE TITLE
clab rec

### ISSUE THREAD

**Issue by BurlyLuo** [BurlyLuo/clab#2]
1.  后台运行
```
    ipsec1:
      kind: linux
      image: 192.168.2.100:5000/nettool
      exec:
      - ip addr add 10.1.5.10/24 dev eth2
      - ip r a 10.1.8.0/24 via 10.1.5.1 dev eth2
      - ip r a 10.1.9.0/24 via 10.1.5.1 dev eth2
      - bash -c "ip x m all > /ip-xfrm-monitor.txt &"
```

2.  timezone
```
      env:
        TZ: Asia/Shanghai
```

3.   mtu
```
  links:
    - endpoints: ["ipsec1:eth2", "gwx:net1"]
      mtu: 1500

    - endpoints: ["ipsec2:eth2", "gwx:net2"]
      mtu: 1500
```
